name: pydata-theme-dev
channels:
  - conda-forge
dependencies:
  - yarn
  - nodejs>=14,<15 # We should use whatever the LTS is at https://nodejs.org/en/
  - "python=3.10"
  - pip
  - pip:
      - -r docs/requirements.txt
