name: Setup PST CI environment
description: Create a PST dev environment

inputs:
  python-version:
    description: Default Python version to use if none is specified
    required: false
    default: "3.12"
  pandoc:
    description: Whether this should install pandoc or not
    required: false
    type: boolean
    default: false
  graphviz:
    description: Whether this should install pandoc or not
    required: false
    type: boolean
    default: false

runs:
  using: composite
  steps:
    - name: "Setup Python 🐍"
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        cache: "pip"
        cache-dependency-path: "pyproject.toml"
        allow-prereleases: true

    - run: python -Im pip install tox-uv
      shell: bash

    # waiting for https://github.com/nikeee/setup-pandoc/pull/8
    # using 12rambau fork until then
    - name: "Install pandoc 📝"
      uses: 12rambau/setup-pandoc@test
      if: ${{ inputs.pandoc }} == true

    - name: "Install Graphviz on Windows 🗔"
      if: runner.os == 'Windows' && ${{ inputs.graphviz }} == true
      shell: bash
      run: choco install graphviz

    - name: "Install Graphviz on macOS "
      if: runner.os == 'macOS' && ${{ inputs.graphviz }} == true
      shell: bash
      run: |
        brew update
        brew install graphviz

    - name: "Install Graphviz on Linux 🐧"
      if: runner.os == 'Linux' && ${{ inputs.graphviz }} == true
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends graphviz
