name: pst-setup-python

# this is a reusable workflow that is called by our other workflows, but should
# not be run itself.

on:
  workflow-call:
    inputs:
      python-version:
        required: true
        type: string

jobs:
  pst-setup-python:
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}
          cache: "pip"
          cache-dependency-path: "pyproject.toml"
      - run: python -m pip install --upgrade pip wheel setuptools
